export const initialMockItems = [
  { _id: 'mock1', category: 'Electronics', title: 'Casio FX-991EX Scientific Calculator', description: 'Used for 1 semester, in perfect working condition. Great for engineering students.', price: 15.00, imageUrl: 'https://picsum.photos/seed/calc/600/400', owner: { name: 'Alex Johnson', email: 'alex.j@college.edu', phone: '555-0101' } },
  { _id: 'mock2', category: 'Textbooks', title: 'Introduction to Algorithms (4th Edition)', description: 'Hardcover algorithms textbook. A must-have for computer science core classes. Minor highlights.', price: 45.00, imageUrl: 'https://picsum.photos/seed/book1/600/400', owner: { name: 'Sarah Smith', email: 'sarah.smith@college.edu', phone: '555-0102' } },
  { _id: 'mock3', category: 'Textbooks', title: 'Calculus Early Transcendentals', description: 'Selling my calc book. Good condition.', price: 30.00, imageUrl: 'https://picsum.photos/seed/book2/600/400', owner: { name: 'Mike Ross', email: 'm.ross@college.edu', phone: '555-0103' } },
  { _id: 'mock4', category: 'Electronics', title: 'Apple iPad Air (4th Gen) 64GB', description: 'Perfect for taking digital notes. Screen protector applied since day 1. Includes case.', price: 250.00, imageUrl: 'https://picsum.photos/seed/ipad/600/400', owner: { name: 'Emma Davis', email: 'emma.davis@college.edu', phone: '555-0104' } },
  { _id: 'mock5', category: 'Dorm Essentials', title: 'Organic Chemistry Model Kit', description: 'Molecular model kit with all parts included. Helps visualize structures for O-Chem.', price: 12.00, imageUrl: 'https://picsum.photos/seed/chem/600/400', owner: { name: 'James Wilson', email: 'j.wilson@college.edu', phone: '555-0105' } },
  { _id: 'mock6', category: 'Electronics', title: 'Sony WH-1000XM4 Noise Cancelling Headphones', description: 'Best headphones for studying in loud environments. Comes with carrying case.', price: 180.00, imageUrl: 'https://picsum.photos/seed/sony/600/400', owner: { name: 'Olivia Brown', email: 'o.brown@college.edu', phone: '555-0106' } },
  { _id: 'mock7', category: 'Electronics', title: 'Mechanical Keyboard (Red Switches)', description: 'Compact 60% mechanical keyboard, great for programming. Very clean.', price: 40.00, imageUrl: 'https://picsum.photos/seed/keyb/600/400', owner: { name: 'David Lee', email: 'd.lee@college.edu', phone: '555-0107' } },
  { _id: 'mock8', category: 'Notes', title: 'Biology Notes (Full Semester)', description: 'Neatly written, color-coded notes for BIO 101. Scanned to PDF or physical copy available.', price: 10.00, imageUrl: 'https://picsum.photos/seed/notes/600/400', owner: { name: 'Emily Clark', email: 'e.clark@college.edu', phone: '555-0108' } },
  { _id: 'mock9', category: 'Dorm Essentials', title: 'Mini Fridge for Dorm', description: 'Small fridge perfect for dorm rooms. Used for one year, works perfectly and runs quiet.', price: 65.00, imageUrl: 'https://picsum.photos/seed/fridge/600/400', owner: { name: 'Chris Evans', email: 'c.evans@college.edu', phone: '555-0109' } },
  { _id: 'mock10', category: 'Other', title: 'Art Supplies Bundle', description: 'Leftover supplies from intro to art class. Includes sketchbooks, charcoal, and acrylics.', price: 20.00, imageUrl: 'https://picsum.photos/seed/art/600/400', owner: { name: 'Sophia Taylor', email: 's.taylor@college.edu', phone: '555-0110' } }
];
